// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCq9PPjsL3ZgIWqXciJtCWLxYRUgfhrfE',
    appId: '1:400485951786:web:bc18f6d4d01c8e2acd9653',
    messagingSenderId: '400485951786',
    projectId: 'fultter-insta-c0486',
    authDomain: 'fultter-insta-c0486.firebaseapp.com',
    storageBucket: 'fultter-insta-c0486.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31LGWsLCxfsMVQZ__mdxFFMje4nJQH6Q',
    appId: '1:400485951786:android:b12bdec556f94c15cd9653',
    messagingSenderId: '400485951786',
    projectId: 'fultter-insta-c0486',
    storageBucket: 'fultter-insta-c0486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4sRT2FLyWZSxL29NIW3uhtSrmuFqD0o',
    appId: '1:400485951786:ios:cec15bd42438588ecd9653',
    messagingSenderId: '400485951786',
    projectId: 'fultter-insta-c0486',
    storageBucket: 'fultter-insta-c0486.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh4sRT2FLyWZSxL29NIW3uhtSrmuFqD0o',
    appId: '1:400485951786:ios:cec15bd42438588ecd9653',
    messagingSenderId: '400485951786',
    projectId: 'fultter-insta-c0486',
    storageBucket: 'fultter-insta-c0486.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCq9PPjsL3ZgIWqXciJtCWLxYRUgfhrfE',
    appId: '1:400485951786:web:6bc9a351d247a684cd9653',
    messagingSenderId: '400485951786',
    projectId: 'fultter-insta-c0486',
    authDomain: 'fultter-insta-c0486.firebaseapp.com',
    storageBucket: 'fultter-insta-c0486.firebasestorage.app',
  );
}
